excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://calzinispaiati.github.io
title: Awesome
email: 
author: calzinispaiati
description: My awesome new site
paginate: 3
google_analytics: 